spring.cloud.gateway.httpclient.codec.multipart.enabled: true
spring.cloud.gateway.httpclient.max-request-size: 1000MB
server:
  port: 8081

security-constraints:
  open-uri:
    - /actuator/**
    - /api/v1/*/api-doc
    - /webjars/swagger-ui/**
    - /swagger-ui**
    - /v3/api-docs/**
    - /api/v1/preview-stories
    - /api/v1/preview-bonus-stories
    - /api/v1/accounts
    - /api/v1/accounts/**
    - /api/v1/stories/*
    - /api/v1/stories/*/glossary
    - /api/v1/authors/*/stories
    - /api/v1/authors/*/stories/**
    - /api/v1/dictionary
    - /api/v1/dictionary/*
    - /api/v1/notifications/**
    - /api/v1/stories-release-dates/*
    - /api/v1/stories/release-checker
    - /api/v2/accounts
    - /api/v2/accounts/**
    - /api/v2/accounts/apple/receipt/transaction
    - /api/v1/subscriptions
    - /api/v1/subscriptions/*/offers
    - /api/v1/subscriptions/*/offers/*/eligibility
    - /api/v1/subscriptions/*/offers/*/discount


cors:
  allowedOrigins: "*"
  allowedMethods: "*"
  allowedHeaders: "*"
  allowedCredentials: true
  maxAge: "3600"

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 50s
      forwarded:
        enabled: true
      x-forwarded:
        enabled: true
        forEnabled: true
        protoEnabled: true
        portEnabled: true
        prefixEnabled: true
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: false
      routes:
        - id: story-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/accounts/*/stories, /api/v1/accounts/*/bonus-stories, /api/v1/preview-stories, /api/v1/preview-bonus-stories, /api/v1/stories/*/glossary, /api/v1/story-service/api-doc, /api/v1/stories-release-dates/*, /api/v1/stories/timeline/month/*/year/*, /api/v2/accounts/*/stories, /api/v2/accounts/*/bonus-stories, /api/v1/stories/release-checker, /api/v2/accounts/apple/receipt/transaction
            - Method=GET
        - id: story-files
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/stories/*/files, /api/v1/stories/*/files/*
            - Method=GET, POST, DELETE
        - id: school-stories
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/school/stories, /api/v1/school/stories/top, /api/v1/school/stories/hero, /api/v1/school/stories/*
            - Method=GET, POST, PUT, PATCH, DELETE
        - id: story-author
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/authors/*/stories, /api/v1/authors/*/stories/**
            - Method=POST,GET,PUT,PATCH
          metadata:
            auth-roles:
              - story-author
          filters:
            - AddPrincipalToPathFilter
        - id: story-admin
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/stories, /api/v1/stories/**, /api/v1/stories/*/release, /api/v1/stories/*/disable, /api/v1/stories/school
            - Method=GET,PATCH,DELETE
          metadata:
            auth-roles:
              - story-admin
        - id: story-admin-roles
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/users/*/roles
            - Method=POST,PUT
          metadata:
            auth-roles:
              - story-admin
        - id: customer-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/accounts/*/status, /api/v1/customer-service/api-doc, /api/v1/accounts/transaction/*, /api/v1/accounts/gift-subscriptions, /api/v1/accounts/gift-subscriptions/redeem, /api/v2/accounts, /api/v2/accounts/**, /api/v2/accounts/*/favorite-stories, /api/v2/accounts/*/favorite-stories/*, /api/v2/accounts/gift-subscriptions, /api/v2/accounts/gift-subscriptions/redeem, /api/v2/accounts/definitions, /api/v1/dictionary, /api/v1/dictionary/*
            - Method=GET
        - id: customer-service-creation
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/accounts, /api/v1/notifications/*
            - Method=POST
        - id: customer-service-favorite-stories
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/accounts/*/favorite-stories, /api/v1/accounts/*/favorite-stories/*
            - Method=POST,GET,DELETE
        - id: subscription-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/subscriptions, /api/v1/subscriptions/*/offers, /api/v1/subscriptions/*/offers/*/eligibility, /api/v1/subscriptions/*/offers/*/discount
            - Method=POST,GET
        - id: multimedia-author
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/multimedia, /api/v1/multimedia/**
          metadata:
            auth-roles:
              - story-author
        - id: multimedia-manager
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/multimedia-manager/api-doc
            - Method=GET
        - id: openapi
          uri: http://localhost:8081
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /api/v1//$\{path}/api-doc
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
          issuer-uri: '{cipher}74b0e6201e3f5cc9a5bc030891430baefd06e3e33df0e35864ef6228f6942a317d18cddd4f34cca77a266e215f69de3d5541e16e1d0eabfbc842fe3695c13f0b'
management:
  endpoints:
    web:
      exposure:
        include: '*'

health:
  config:
    enabled: false

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    reactor.netty.http.client: DEBUG

springdoc:
  packages-to-scan: com.agenatech.customer.controller, com.agenatech.story.controller, com.agenatech.multimedia.controller
  custom:
    ignored-routes:
      - openapi
      - story-author
      - story-admin
      - multimedia-author
