spring:
  cloud:
    gateway:
      routes:
        - id: story-user
          uri: http://story-service
          predicates:
            - Path=/api/v1/stories/day
            - Method=GET
        - id: story-author
          uri: http://story-service
          predicates:
            - Path=/api/v1/stories, /api/v1/stories/**
            - Method=POST,GET,PUT,PATCH,DELETE
          metadata:
            auth-roles:
              - story-admin
              - story-author
        - id: story-admin
          uri: http://story-service
          predicates:
            - Path=/api/v1/stories/*/release
            - Method=PATCH
          metadata:
            auth-roles:
              - story-admin
        - id: customer-service
          uri: http://customer-service
          predicates:
            - Path=/api/v1/accounts, /api/v1/accounts/**, /api/v1/notifications/**
            - Method=POST,GET
        - id: multimedia
          uri: http://multimedia-manager
          predicates:
            - Path=/api/v1/multimedia, /api/v1/multimedia-manager/**
          metadata:
            auth-roles:
              - story-admin
              - story-author
        - id: openapi
          uri: http://api-gateway
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /api/v1//$\{path}/api-doc
