spring.cloud.gateway.httpclient.codec.multipart.enabled: true
spring.cloud.gateway.httpclient.max-request-size: 1000MB
server:
  port: 8081

security-constraints:
  open-uri:
    - /actuator/**
    - /api/v1/*/api-doc
    - /webjars/swagger-ui/**
    - /swagger-ui**
    - /v3/api-docs/**
    - /api/v1/preview-stories
    - /api/v1/preview-bonus-stories
    - /api/v1/accounts
    - /api/v1/accounts/**
    - /api/v1/stories/*
    - /api/v1/stories/*/glossary
    - /api/v1/authors/*/stories
    - /api/v1/authors/*/stories/**
    - /api/v1/dictionary
    - /api/v1/dictionary/*
    - /api/v1/notifications/**
    - /api/v1/stories-release-dates/*
    - /api/v1/stories/release-checker
    - /api/v2/accounts
    - /api/v2/accounts/**


cors:
  allowedOrigins: "*"
  allowedMethods: "*"
  allowedHeaders: "*"
  allowedCredentials: true
  maxAge: "3600"

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 50s
      forwarded:
        enabled: true
      x-forwarded:
        enabled: true
        forEnabled: true
        protoEnabled: true
        portEnabled: true
        prefixEnabled: true
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: false
      routes:
        - id: story-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/accounts/*/stories, /api/v1/accounts/*/bonus-stories, /api/v1/preview-stories, /api/v1/preview-bonus-stories, /api/v1/stories/*/glossary, /api/v1/story-service/api-doc, /api/v1/stories-release-dates/*, /api/v1/stories/timeline/month/*/year/*, /api/v2/accounts/*/stories, /api/v2/accounts/*/bonus-stories, /api/v1/stories/release-checker
            - Method=GET
        - id: story-author
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/authors/*/stories, /api/v1/authors/*/stories/**
            - Method=POST,GET,PUT,PATCH
          metadata:
            auth-roles:
              - story-author
          filters:
            - AddPrincipalToPathFilter
        - id: story-admin
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/stories, /api/v1/stories/**, /api/v1/stories/*/release, /api/v1/stories/*/disable
            - Method=GET,PATCH,DELETE
          metadata:
            auth-roles:
              - story-admin
        - id: customer-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/accounts/*/status, /api/v1/customer-service/api-doc, /api/v1/accounts/transaction/*, /api/v1/accounts/gift-subscriptions, /api/v1/accounts/gift-subscriptions/redeem, /api/v2/accounts, /api/v2/accounts/**, /api/v2/accounts/*/favorite-stories, /api/v2/accounts/*/favorite-stories/*, /api/v2/accounts/gift-subscriptions, /api/v2/accounts/gift-subscriptions/redeem, /api/v2/accounts/definitions, /api/v1/dictionary, /api/v1/dictionary/*
            - Method=GET
        - id: customer-service-creation
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/accounts, /api/v1/notifications/*
            - Method=POST
        - id: customer-service-favorite-stories
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/accounts/*/favorite-stories, /api/v1/accounts/*/favorite-stories/*
            - Method=POST,GET,DELETE
        - id: multimedia-author
          uri: http://localhost:8097
          predicates:
            - Path=/api/v1/multimedia, /api/v1/multimedia/**
          metadata:
            auth-roles:
              - story-author
        - id: multimedia-manager
          uri: http://localhost:8097
          predicates:
            - Path=/api/v1/multimedia-manager/api-doc
            - Method=GET
        - id: openapi
          uri: http://localhost:8081
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /api/v1//$\{path}/api-doc
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: web
            authorization-grant-type: authorization_code
            redirect-uri: ${keycloak-client.server-url}/login/oauth2/code/keycloak
            scope: openid
        provider:
          keycloak:
            authorization-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/auth
            token-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/token
            user-info-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
            user-name-attribute: name
            user-info-authentication-method: header
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
keycloak-client:
  server-url: https://auth.astoryaday.se/auth
  realm: a-story-a-day
management:
  endpoints:
    web:
      exposure:
        include: '*'

health:
  config:
    enabled: false

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    reactor.netty.http.client: DEBUG

springdoc:
  packages-to-scan: com.agenatech.customer.controller, com.agenatech.story.controller, com.agenatech.multimedia.controller
  custom:
    ignored-routes:
      - openapi
      - story-author
      - story-admin
      - multimedia-author
