server.port: 8082
spring:
  application:
    name: story-service
  datasource:
    url: jdbc:postgresql://localhost:5432/story-service?ssl=false
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
logging:
  level:
    com.agenatech: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
account:
  url: http://localhost:8083
springdoc.api-docs.path: /api/v1/story-service/api-doc
happyscribe:
  api-key: '{cipher}88c6de294f596ccba1823032d3cc634a65be7b1e04e3363fa1e4fa83b699598e678cae26e7a79ee964eb011cebd22b2e'
  organization-id: '{cipher}94c3d43e057b41cd90458568a4c5b5d4eca7be9b4edd2ef5dab509b4c5eead8a'
  api-url: https://www.happyscribe.com/api/v1
multimedia:
  url: https://api-dev.astoryaday.se/api/v1/multimedia
groq.api-key: '{cipher}654555e7e423923559f33a85e3abfe4fbbc9b568df70980d71b427906144edc6285224e37fe2c083aa371f4f22ea39d4b80091a6b824690b7ed2d83ca9b5482c3357be5ec13f2f03cf053c951eacd666'
groq.api-url: 'https://api.groq.com/openai/v1/chat/completions'