server.port: 8082
spring:
  application:
    name: story-service
  datasource:
    url: jdbc:postgresql://localhost:5432/story-service?ssl=false
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
logging:
  level:
    com.agenatech: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
account:
  url: http://localhost:8083
springdoc.api-docs.path: /api/v1/story-service/api-doc