server.port: 8083
spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/customer-service?ssl=false
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
apple:
  url: https://api.storekit.itunes.apple.com
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: basic
springdoc.api-docs.path: /api/v1/customer-service/api-doc
logging:
  level:
    com.agenatech: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG