server.port: 8083
spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/customer-service?ssl=false
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
apple:
  url: https://sandbox.itunes.apple.com
  url-sandbox: https://sandbox.itunes.apple.com
  verify-receipt-url: verifyReceipt
  secret: 1234
google:
  url: https://androidpublisher.googleapis.com
  verify-receipt-url: androidpublisher/v3/applications/${google.package-name}/purchases/subscriptions/{subscriptionId}/tokens/{token}
  package-name: com.astoryadayab.astoryaday
  secret: 1234
story:
  url: http://localhost:8082
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: basic
springdoc.api-docs.path: /api/v1/customer-service/api-doc
logging:
  level:
    com.agenatech: DEBUG
